### ISSUE TITLE
Fails to build with GCC-16 and Qt5 6.10 on Debian Sid

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#1603]
### Operating System Info

Other

### Other OS

Debian Sid (unstable)

### OBS Studio Version

32.1.2

### Advanced Scene Switcher Version

1.33.1

### Expected Behavior

A good build.

### Current Behavior

Dear @WarmUpTill 

When building on Debian Sid:

```
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher-1.33.1/tests/test-macro-condition-file.cpp:16:15: error: ignoring return value of ‘virtual bool QFile::open(QIODeviceBase::OpenMode)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
   16 |         f.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/QFile:1,
                 from /PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher-1.33.1/tests/test-macro-condition-file.cpp:5:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qfile.h:291:32: note: declared here
  291 |     QFILE_MAYBE_NODISCARD bool open(OpenMode flags) override;
      |                                ^~~~
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher-1.33.1/tests/test-macro-condition-file.cpp: In function ‘void C_A_T_C_H_T_E_S_T_16()’:
/PKGS/obs-advanced-scene-switcher/obs-advanced-scene-switcher-1.33.1/tests/test-macro-condition-file.cpp:158:15: error: ignoring return value of ‘virtual bool QFile::open(QIODeviceBase::OpenMode)’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  158 |         f.open(QIODevice::ReadWrite);

```
I attached a full log.

Thanks!

[obs-advanced-scene-switcher_1.33.1-1_amd64.build.gz](https://github.com/user-attachments/files/27171627/obs-advanced-scene-switcher_1.33.1-1_amd64.build.gz)

### Steps to Reproduce

1.
2.
3.
...

**Comment by WarmUpTill** [comment]
Sorry about that!

The issues should be resolved with the changes on the `test` branch.
If not, please do let me know!

**Comment by eribertomota** [comment]
Hi! It worked fine! Thanks!
