### ISSUE TITLE
Tons of repeated OpenSSL-related errors when building

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1641]
### Operating System Info

Windows 10

### OBS Studio Version

32.1.2

### Advanced Scene Switcher Version

master

### Expected Behavior

The build should go through.

### Current Behavior

There are lots of errors such as:
```
D:\Dev\Repositories\git\OBS-AdvancedSceneSwitcher\deps\cpp-httplib\httplib.h(8700,21): warning C4996: 'X509_NAME_get_text_by_NID': Since OpenSSL 4.0 [D:\Dev\Repositories\git\
OBS-AdvancedSceneSwitcher\build_x64\plugins\http\advanced-scene-switcher-http.vcxproj]
D:\Dev\Repositories\git\OBS-AdvancedSceneSwitcher\deps\cpp-httplib\httplib.h(8700,21): error C2220: następujące ostrzeżenie jest traktowane jako błąd [D:\Dev\Repositories\git
\OBS-AdvancedSceneSwitcher\build_x64\plugins\http\advanced-scene-switcher-http.vcxproj]
D:\Dev\Repositories\git\OBS-AdvancedSceneSwitcher\deps\asio\asio\include\asio\ssl\impl\rfc2818_verification.ipp(65,11): error C2027: wykorzystanie niezdefiniowanego przez uży
tkownika typu "asn1_string_st" [D:\Dev\Repositories\git\OBS-AdvancedSceneSwitcher\build_x64\plugins\twitch\advanced-scene-switcher-twitch.vcxproj]
```
when attempting to build with OpenSSL 4.0.1 installed on Windows 10, which I guess is chosen with `include(cmake/windows/wingetssl.cmake)`.

### Steps to Reproduce

1. Install OpenSSL 4 in Windows
2. Run `.github/scripts/Build-Windows.ps1`

### Anything else we should know?

Adding `add_definitions(-DOPENSSL_API_COMPAT=10101)` to AdvSS CMakeLists.txt gets rid of first 2 errors, but the 3rd is still there and a very common occurence. Not sure if that's any sort of a solution even if it fixed all 3. Is there any better workaround?

**Comment by WarmUpTill** [comment]
Unfortunately, I don't think this is solvable at the moment.
I tried switching to OpenSSL 4 on Windows a month or two ago, but this require updating various other dependencies, which ultimately resulted in a conflict between library versions used by OBS and the plugin. (I think it was `asio`, but not 100% sure)

Thus I pinned OpenSSL to version 3.X for now with https://github.com/WarmUpTill/SceneSwitcher/commit/c5185765eefa8bd686cd2659873ec274ee331da6.

I will leave this issue open for now as a reminder to maybe try again at later date.
Thanks for creating the issue!

**Comment by Destroy666x** [comment]
I see, thanks.

**Comment by Destroy666x** [comment]
BTW @WarmUpTill , do I remember correctly that unavailable actions/conditions get deleted from scene collection? Is there a better way to preserve them than going through all macros and backing up the ones that have my custom stuff that I never got to finish? As I'd like to test some new stuff without necessarily losing the WIP/test stuff I had as I may come back to that later this year

**Comment by WarmUpTill** [comment]
You do remember that correctly.
That was the case for quite a while, but was resolved with https://github.com/WarmUpTill/SceneSwitcher/commit/badce063eb60c23d5d367f9095c43933a7e89224.

**Comment by Destroy666x** [comment]
Ah, good change, thanks for info.
